<?php

// A short string that does not appear in table or field names.
define('DATA_ENGINE_DB_PLACEHOLDER', 'qxq');

/**
 * Implements hook_cron().
 * Checks for new data sets.
 */
/*
function data_engine_db_cron() {

  data_engine_db_sync_taxonomy_from_reference('ref_geographic_level', 'location_types', 1);
  data_engine_db_sync_taxonomy_from_reference('ref_domain', 'data_categories', 2);
  data_engine_db_sync_taxonomy_from_reference('ref_subdomain', 'data_categories', 2, 'ref_domain');
  data_engine_db_sync_taxonomy_from_reference('ref_source', 'sources', 5);

  $datasets = data_engine_db_datasets();
  $queue = DrupalQueue::get('data_engine_db_dataset_updates');
  $count = $queue->numberOfItems();

  $node_saved = FALSE;

  foreach ($datasets as $id) {

    $info = data_engine_db_dataset_info($id, TRUE);

    if ($info['nid'] == '') {

      if (!$node_saved) {
  
        $info = data_engine_db_dataset_info($id);
        $node = data_engine_db_node_from_info($info);
        node_save($node);
        data_engine_db_set_dataset_nid($info, $node->nid);
        $node_saved = TRUE;

      } // if
      
    } // if
    elseif ($count == 0) {

      // Queue updated datasets for re-saving.

      $info = data_engine_db_dataset_info($id);      
      $queue->createItem($info);

    } // else

  } // foreach

} // data_engine_db_cron
*/

/**
 * Implements hook_cron_queue_info().
 */
function data_engine_db_cron_queue_info() {

  $queues['data_engine_db_dataset_updates'] = array(
    'worker callback' => 'data_engine_db_dataset_update',
    'time' => 20,
  );
  return $queues;

} // data_engine_db_cron_queue_info

/**
 * Updates a dataset based on NID.
 */
function data_engine_db_update_dataset_for_nid($nid) {
  
  $node = node_load($nid);
  $info = data_engine_db_info_for_node($node);

  $info = data_engine_db_dataset_info($info->id);

  data_engine_db_dataset_update($info);
  
} // data_engine_db_update_dataset_for_nid

/**
 * Updates a given dataset, based on info.
 */
function data_engine_db_dataset_update($info) {

  $node = node_load($info['nid']);
  
  if ($node) {

    $original_node = clone $node;
    $updated_node = data_engine_db_node_from_info($info, $node);
    
    $original_wrapper = entity_metadata_wrapper('node', $original_node);
    $updated_wrapper = entity_metadata_wrapper('node', $updated_node);

    node_save($updated_node);

  } // if
  else {
    dpm($info, 'node not found');
    watchdog('data_engine_db', 'Node not found: ' . $info['nid'] . ' for dataset: ' . $info['id'], WATCHDOG_ERROR);
  } // else

} // data_engine_db_dataset_update

/**
 * Returns list of data set IDs in DB.
 */
function data_engine_db_datasets() {

  $ids = array();

  db_set_active('data');

  $results = db_query('SELECT id FROM datasets');

  foreach ($results as $result) {
    $ids[] = $result->id;
  } // foreach

  db_set_active('default');

  return $ids;

} // data_engine_db_datasets

/**
 * Returns reference table from DB.
 */
function data_engine_db_reference_table($table_name) {
  
  $records = array();

  db_set_active('data');

  $results = db_query('SELECT * FROM ' . $table_name);

  foreach ($results as $result) {
    $records[$result->id] = $result;
  } // foreach

  db_set_active('default');

  return $records;
  
} // data_engine_db_reference_table

/**
 * Returns term from a refernce ID.
 */
function data_engine_db_term_from_reference_id($id, $table_name, $vocabulary_name, $full_term = TRUE) {

  $query = new EntityFieldQuery();
  $entities = $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->entityCondition('bundle', $vocabulary_name)
    ->fieldCondition('field_database_id', 'value', $id)
    ->fieldCondition('field_database_table', 'value', $table_name)
    ->range(0, 1)
    ->execute();
  
  if (isset($entities['taxonomy_term']) && count($entities['taxonomy_term']) > 0) {
  
    $tids = array_keys($entities['taxonomy_term']);
    
    if (!$full_term) {
      return $tids[0];
    } // if
    
    $terms = entity_load('taxonomy_term', $tids);
    return array_shift($terms);
    
  } // if
  else {

    $query = new EntityFieldQuery();
    $entities = $query
      ->entityCondition('entity_type', 'taxonomy_term')
      ->entityCondition('bundle', $vocabulary_name)
      ->fieldCondition('field_database_id', 'value', $id)
      ->range(0, 1)
      ->execute();

    if (isset($entities['taxonomy_term']) && count($entities['taxonomy_term']) > 0) {

      $tids = array_keys($entities['taxonomy_term']);
      $terms = entity_load('taxonomy_term', $tids);
      $term = array_shift($terms);
      $term_wrapper = entity_metadata_wrapper('taxonomy_term', $term);
      
      if ($term_wrapper->field_database_table->value() == '') {

        if (!$full_term) {
          return $tids[0];
        } // if
  
        $terms = entity_load('taxonomy_term', $tids);
        return array_shift($terms);

      } // if

    } // if
    
  } // else

  return FALSE;
    
} // data_engine_db_term_from_reference_id

/**
 * Syncs a taxonomy from a reference table.
 */
function data_engine_db_sync_taxonomy_from_reference($table_name, $vocabulary_name, $vid, $parent_table = FALSE) {

  $records = data_engine_db_reference_table($table_name);

  foreach ($records as $id => $record) {
    
    $term_id = data_engine_db_term_from_reference_id($id, $table_name, $vocabulary_name, FALSE);

    if (!$term_id) {

      if (isset($record->parent_id) && $parent_table) {      
        $parent_term_id = data_engine_db_term_from_reference_id($record->parent_id, $parent_table, $vocabulary_name, FALSE);
        $term = entity_create('taxonomy_term', array('vocabulary_machine_name' => $vocabulary_name, 'name' => $record->name, 'vid' => $vid, 'parent' => $parent_term_id));
      } // if
      else {
        $term = entity_create('taxonomy_term', array('vocabulary_machine_name' => $vocabulary_name, 'name' => $record->name, 'vid' => $vid));
      } // else

    } // if
    else {      
      $term = taxonomy_term_load($term_id);
    } // else
    
    $term_wrapper = entity_metadata_wrapper('taxonomy_term', $term);
    $term_wrapper->field_database_id->set($id);
    $term_wrapper->field_database_table->set($table_name);

    taxonomy_term_save($term);

  } // foreach
  
} // data_engine_db_sync_taxonomy_from_reference

/**
 * Returns list of data set nodes in Drupal.
 */
function data_engine_db_dataset_nodes() {

  $nodes = array();

  $query = new EntityFieldQuery();
  $entities = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'dataset')
    ->execute();

  $nids = array();

  if (isset($entities['node']) && count($entities['node']) > 0) {
    $nids = array_keys($entities['node']);
  } // if
  
  return entity_load('node', $nids);

} // data_engine_db_dataset_nodes

/**
 * Returns information about a given dataset.
 */
function data_engine_db_dataset_info($id, $skip_tables = FALSE) {

  $info = array('id' => $id);

  db_set_active('data');

  $object = db_query('SELECT metadata FROM datasets WHERE id = :id', array(':id' => $id))->fetchObject();

  $json = json_decode($object->metadata);

  $info['title'] = $json->name;
  $info['nid'] = $json->nid;
  $info['metadata'] = $json;

  if (!$skip_tables) {

    $info['tables'] = array();

    foreach ($json->tables as $table_id) {
      $info['tables'][] = data_engine_db_table_info($table_id);
    } // foreach

    list($geo_table_id, $field) = explode('.', $info['metadata']->gkey[1]);
    $info['geo_table'] = data_engine_db_geo_table_info($geo_table_id);

  } // if

  db_set_active('default');

  return $info;

} // data_engine_db_dataset_info

/**
 * Returns information about a given table.
 */
function data_engine_db_table_info($id) {

  $info = array();

  db_set_active('data');

  $object = db_query('SELECT m.*, t.table_name FROM data_tables_metadata m JOIN data_tables t ON t.id = m.id WHERE t.id = :id', array(':id' => $id))->fetchObject();

  $json = json_decode($object->metadata);

  $info['id'] = $object->id;
  $info['title'] = $object->table_name;
  $info['fields'] = $json->field_metadata;
  $info['tags'] = (array)$json->table_tags;

  db_set_active('default');

  $field_machine_names = data_engine_db_fields_in_table($info['title']);

  foreach ($info['fields'] as $key => $field) {
    if ($field->field_name != '') {
      $info['fields'][$key]->machine_name = $field->field_name;
    } // if
    elseif (isset($field_machine_names[$key])) {
      $info['fields'][$key]->machine_name = $field_machine_names[$key];
    } // elseif
  } // foreach

  return $info;

} // data_engine_db_table_info

/**
 * Returns information about a given geo table.
 */
function data_engine_db_geo_table_info($id) {

  $info = array();

  db_set_active('data');

  $object = db_query('SELECT t.id, t.table_name FROM data_tables t WHERE t.id = :id', array(':id' => $id))->fetchObject();

  $info['id'] = $object->id;
  $info['title'] = $object->table_name;

  db_set_active('default');

  return $info;

} // data_engine_db_geo_table_info

/**
 * Returns ordered list of fields in a given table.
 */
function data_engine_db_fields_in_table($table) {

  $fields = array();

  db_set_active('data');

  $result = db_query('SELECT a.attname FROM  pg_attribute a, pg_class c WHERE c.relname = :table AND a.attnum > 0 AND a.attrelid = c.oid ORDER BY a.attnum', array(':table' => $table));

  foreach ($result as $record) {
    $fields[] = $record->attname;
  } // foreach

  db_set_active('default');

  return $fields;

} // data_engine_db_fields_in_table

/**
 * Creates (does not save) a new node from a DB dataset record.
 */
function data_engine_db_node_from_info($info, $node = FALSE) {

  if ($node == FALSE) {
    $node = entity_create('node', array('type' => 'dataset', 'title' => $info['title']));
  } // if
  else {
    $node->title = $info['title'];
  } // else

  $json = json_encode($info);  

  $wrapper = entity_metadata_wrapper('node', $node);
  $wrapper->field_query_information->set($json);
  
  $first_table = array_shift($info['tables']);

  // Set year
  
  if (isset($first_table['tags']['year'])) {
    $wrapper->field_date_range->set($first_table['tags']['year']);
  } // if
  
  // Set large

  if (isset($info['metadata']->large_dataset)) {
    $wrapper->field_large_dataset->set($info['metadata']->large_dataset);
  } // if

  // Set source

  if (isset($first_table['tags']['source']) && $first_table['tags']['source'] != '') {

    $source_term = data_engine_db_term_from_reference_id($first_table['tags']['source'], 'ref_source', 'sources');

    if ($source_term) {

      $source = entity_create('field_collection_item', array('field_name' => 'field_organization'));
      $source->setHostEntity('node', $node);
      $source_wrapper = entity_metadata_wrapper('field_collection_item', $source);
      $source_wrapper->field_organization_name->set($source_term);

      // Set source website

      if (isset($first_table['tags']['source_website']) && $first_table['tags']['source_website'] != '') {
        $source_wrapper->field_website->url->set($first_table['tags']['source_website']);
      } // if

      $source->save(TRUE);

    } // if

  } // if

  // Set description
  
  if (isset($first_table['tags']['description']) && $first_table['tags']['description'] != '') {
    $wrapper->body->value->set($first_table['tags']['description']);
  } // if
  
  // Set data considerations
  
  if (isset($first_table['tags']['data_consideration']) && $first_table['tags']['data_consideration'] != '') {
    $wrapper->field_data_considerations->value->set($first_table['tags']['data_consideration']);
  } // if
  
  // Set location type
  
  if (isset($first_table['tags']['geographic_level']) && $first_table['tags']['geographic_level'] != '') {

    $location_type_term = data_engine_db_term_from_reference_id($first_table['tags']['geographic_level'], 'ref_geographic_level', 'location_types');

    if ($location_type_term) {
      $wrapper->field_location_type->set($location_type_term);      
    } // if

  } // if
  
  // Set categories
  
  if (isset($first_table['tags']['domain']) && $first_table['tags']['domain'] != '') {

    $terms = array();
    $domain_term = data_engine_db_term_from_reference_id($first_table['tags']['domain'], 'ref_domain', 'data_categories');

    if ($domain_term) {
      $terms[] = $domain_term;
    } // if

    if (isset($first_table['tags']['subdomain']) && $first_table['tags']['subdomain'] != '') {
    
      $subdomain_term = data_engine_db_term_from_reference_id($first_table['tags']['subdomain'], 'ref_subdomain', 'data_categories');
    
      if ($subdomain_term) {
        $terms[] = $subdomain_term;
      } // if
    
    } // if

    if (count($terms) > 0) {
      $wrapper->field_data_categories->set($terms);      
    } // if

  } // if

  return $node;

} // data_engine_db_node_from_info

/**
 * Sets the nid value of the dataset record with given info.
 */
function data_engine_db_set_dataset_nid($info, $nid) {

  $metadata = $info['metadata'];
  $metadata->nid = $nid;
  $json = json_encode($metadata);

  db_set_active('data');

  db_query('UPDATE datasets SET metadata = :json WHERE id = :id', array(':json' => $json, ':id' => $info['id']))->fetchObject();

  db_set_active('default');

} // data_engine_db_set_dataset_nid

/**
 * Translate table to alias.
 */
function data_engine_db_table_to_alias(&$table) {

  return 'table' . $table->id;

} // data_engine_db_table_to_alias

/**
 * Translate alias to table.
 */
function data_engine_db_alias_to_table_name($alias) {

  $table_names = &drupal_static(__FUNCTION__); 

  if (!isset($table_names)) {
    $table_names = array();
  } // if

  if (!isset($table_names[$alias])) {

    $id = str_replace('table', '', $alias);

    db_set_active('data');

    $object = db_query('SELECT t.table_name FROM data_tables t WHERE t.id = :id', array(':id' => $id))->fetchObject();
    
    db_set_active('default');

    if ($object) {
      $table_names[$alias] = $object->table_name;
    } // if
    else {
      $table_names[$alias] = $alias;
    } // else

  } // if

  return $table_names[$alias];

} // data_engine_db_alias_to_table

/**
 * Creates a query from a dataset node.
 */
function data_engine_db_query_from_node($node, $skip_fields = FALSE) {

  try {

    $info = data_engine_db_info_for_node($node);

    if ($info) {

      $tables_in_query = array();
      $first_table = array_shift($info->tables);

      db_set_active('data');

      $query = db_select($first_table->title, data_engine_db_table_to_alias($first_table));
      $tables_in_query[] = $first_table;

      if (!$skip_fields) {
        data_engine_db_add_table_fields_to_query($first_table, $query);
      } // if

      if (count($info->tables) > 0) {

        foreach ($info->tables as $table) {

          data_engine_db_join_table_to_query($query, $table, $tables_in_query, $info->metadata);          
          $tables_in_query[] = $table;

          if (!$skip_fields) { 
            data_engine_db_add_table_fields_to_query($table, $query);
          } // if

        } // foreach
        
      } // if

      db_set_active('default');

      return $query;

    } // if
    else {

      return FALSE;

    } // else

  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [NID: ' . $node->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;

  } // catch

} // data_engine_db_query_from_node

/**
 * Creates a query from multiple dataset nodes.
 */
function data_engine_db_query_from_nodes($node_one, $node_two) {
  
  $node_one_wrapper = entity_metadata_wrapper('node', $node_one);
  $node_one_info = json_decode($node_one_wrapper->field_query_information->value());

  $node_one_geo_table = $node_one_info->geo_table;

  // Get query for first node.

  $query = data_engine_db_geo_query_from_node($node_one);
  
  $tables_in_query = $node_one_info->tables;
  $tables_in_query[] = $node_one_geo_table;

  $node_two_wrapper = entity_metadata_wrapper('node', $node_two);
  $node_two_info = json_decode($node_two_wrapper->field_query_information->value());

  try {

    db_set_active('data');

    // Join dataset 2 tables

    foreach ($node_two_info->tables as $table) {
          
      if (data_engine_db_join_table_to_query($query, $table, $tables_in_query, $node_two_info->metadata)) {
        data_engine_db_add_table_fields_to_query($table, $query);
      } // if

    } // foreach
            
    db_set_active('default');

    return $query;

  } // try
  catch (Exception $e) {
  
    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [NIDs: ' . $node_one->nid . '+' . $node_two->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;
  
  } // catch

} // data_engine_db_query_from_nodes

/**
 * Creates a geo query from a dataset node.
 */
function data_engine_db_geo_query_from_node($node, $skip_fields = FALSE) {

  try {

    $wrapper = entity_metadata_wrapper('node', $node);
    $info = json_decode($wrapper->field_query_information->value());

    $first_table = array_shift($info->tables);
    $geo_table = $info->geo_table;

    $query = data_engine_db_query_from_node($node, $skip_fields);

    db_set_active('data');

    data_engine_db_add_query_join_from_metadata($query, $first_table, $geo_table, $info->metadata);

    db_set_active('default');
    
    return $query;

  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [NID: ' . $node->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;

  } // catch

} // data_engine_db_geo_query_from_node

/**
 * Returns array of geo IDs for dataset.
 */
function data_engine_db_geo_ids_from_node(&$node) {

  $wrapper = entity_metadata_wrapper('node', $node);
  $info = json_decode($wrapper->field_query_information->value());

  $query = data_engine_db_geo_query_from_node($node, TRUE);

  $geo_table = $info->geo_table;
  $geo_key = data_engine_db_key_for_table($info->metadata, $geo_table);

  $query->addField(data_engine_db_table_to_alias($geo_table), $geo_key, data_engine_db_table_to_alias($geo_table) . DATA_ENGINE_DB_PLACEHOLDER . $geo_key);
  
  $records = data_engine_db_query_to_records($query);
  
  $ids = array();
  
  foreach ($records as $record) {
    $ids[] = $record[$geo_table->title . '.' . $geo_key];
  } // foreach
  
  return $ids;
  
} // data_engine_db_geo_ids_from_node

/**
 * Return array of values for a given field.
 */
function data_engine_db_values_for_node_key(&$node, $key) {
  
  $values = array();

  $query = data_engine_db_geo_query_from_node($node, TRUE);

  list($table_name, $field) = explode('.', $key);
  
  $table = FALSE;
  
  $table = data_engine_db_table_from_node_by_name($node, $table_name);
    
  if ($table) {
    
    $query->addField(data_engine_db_table_to_alias($table), $field, data_engine_db_table_to_alias($table) . DATA_ENGINE_DB_PLACEHOLDER . $field);
    $query->orderBy(data_engine_db_table_to_alias($table) . DATA_ENGINE_DB_PLACEHOLDER . $field, 'ASC');
    $query->distinct();

    $records = data_engine_db_query_to_records($query);
      
    foreach ($records as $record) {
      $values[] = $record[$table->title . '.' . $field];
    } // foreach

  } // if

  return $values;
  
} // data_engine_db_values_for_node_key

function data_engine_db_table_from_node_by_name(&$node, $table_name) {
  
  $info = data_engine_db_info_for_node($node);
  
  foreach ($info->tables as $table) {
    if ($table->title == $table_name) {
       return $table;
    }
  }
  
  if ($info->geo_table->title == $table_name) {
    return $info->geo_table;
  } // if
  
  return FALSE;
  
} // data_engine_db_table_from_node_by_name

/**
 * Returns array with table => field structure, based on table.field structure.
 */
function data_engine_db_foreign_keys_by_table_id($keys_array) {

  $keys = array();

  foreach ($keys_array as $key_pair) {

    list($first_key, $second_key) = $key_pair;

    list($first_table, $first_field) = explode('.', $first_key);
    list($second_table, $second_field) = explode('.', $second_key);

    $keys[$first_table . '-' . $second_table] = $field;

  } // foreach

  return $keys;

} // data_engine_db_foreign_keys_by_table_id

function data_engine_db_key_for_table(&$metadata, &$table, $join_table = FALSE) {

  $key_pairs = $metadata->fkeys;
  $key_pairs[] = $metadata->gkey;
  
  foreach ($key_pairs as $key_pair) {
    
    list($key_one, $key_two) = $key_pair;
    
    list($pair_table_one, $field_one) = explode('.', $key_one);
    list($pair_table_two, $field_two) = explode('.', $key_two);

    if (
      ($pair_table_one == $table->id) &&
      (!$join_table || $pair_table_two == $join_table->id)
    ) {
    
      return $field_one;

    } // if
    elseif (
      ($pair_table_two == $table->id) &&
      (!$join_table || $pair_table_one == $join_table->id)
    ) {
    
      return $field_two;

    } // elseif

  } // foreach

  return FALSE;

} // data_engine_db_key_for_table

/**
 * Adds join to query based on foreign key metadata.
 */
function data_engine_db_add_query_join_from_metadata(&$query, &$table_one, &$table_two, &$metadata) {
  
  $key_pairs = $metadata->fkeys;
  $key_pairs[] = $metadata->gkey;
  
  foreach ($key_pairs as $key_pair) {
    
    list($key_one, $key_two) = $key_pair;
    
    list($pair_table_one, $field_one) = explode('.', $key_one);
    list($pair_table_two, $field_two) = explode('.', $key_two);
    
    if ($pair_table_one == $table_one->id && $pair_table_two == $table_two->id) {
      
      $query->join($table_two->title, data_engine_db_table_to_alias($table_two), data_engine_db_table_to_alias($table_two) . '.' . $field_two . ' = ' . data_engine_db_table_to_alias($table_one) . '.' . $field_one);
      return TRUE;

    } // if
    elseif ($pair_table_two == $table_one->id && $pair_table_one == $table_two->id) {

      $query->join($table_two->title, data_engine_db_table_to_alias($table_two), data_engine_db_table_to_alias($table_two) . '.' . $field_one . ' = ' . data_engine_db_table_to_alias($table_one) . '.' . $field_two);
      return TRUE;

    } // elseif

  } // foreach
  
  return FALSE;

} // data_engine_db_add_query_join_from_metadata

/**
 * Joins given table to query, based on already-joined tables and metadata.
 */
function data_engine_db_join_table_to_query(&$query, &$new_table, $existing_tables, &$metadata) {
  
  // Look for a join on each table.
  
  foreach ($existing_tables as $existing_table) {
  
    if (data_engine_db_add_query_join_from_metadata($query, $existing_table, $new_table, $metadata)) {
      return TRUE;
    } // if

  } // foreach
  
  return FALSE;
  
} // data_engine_db_join_table_to_query

/**
 * Returns records from a dataset, in range.
 */
function data_engine_db_records_from_node($node, $start = FALSE, $limit = FALSE, $filters = FALSE) {

  try {

    $records = array();

    $info = data_engine_db_info_for_node($node);
    $query = data_engine_db_geo_query_from_node($node);

    if ($info->metadata->display_name) {

      $id_to_name = data_engine_db_table_id_to_name($info);
      list($table_id, $field_name) = explode('.', $info->metadata->display_name);
      $table_name = $id_to_name[$table_id];
      $display_name_table = data_engine_db_table_from_node_by_name($node, $table_name);
      
      $query->addField(data_engine_db_table_to_alias($display_name_table), $field_name, data_engine_db_table_to_alias($display_name_table) . DATA_ENGINE_DB_PLACEHOLDER . $field_name);

    } // if

    if (is_array($filters) && count($filters) > 0) {
      
      foreach ($filters as $filter => $values) {
      
        list($table_name, $field_name) = explode('.', $filter);
        $filter_table = data_engine_db_table_from_node_by_name($node, $table_name);
        $query->condition(data_engine_db_table_to_alias($filter_table) . '.' . $field_name, $values, 'IN');

      } // foreach
      
    } // if

    if ($start !== FALSE && $limit !== FALSE) {
      $query->range($start, $limit);
    } // if

    db_set_active('default');
    
    return data_engine_db_query_to_records($query);

  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [NID: ' . $node->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;

  } // catch

} // data_engine_db_records_from_node

/**
 * Returns records from a dataset, in range.
 */
function data_engine_db_records_from_nodes($node_one, $node_two, $start = FALSE, $limit = FALSE, $filters = FALSE) {

  try {

    $records = array();

    $query = data_engine_db_query_from_nodes($node_one, $node_two);

    db_set_active('data');

    if (is_array($filters) && count($filters) > 0) {
      
      foreach ($filters as $dataset_filters) {
      
        foreach ($dataset_filters as $filter => $values) {
        
          list($table_name, $field_name) = explode('.', $filter);
          $filter_table = data_engine_db_table_from_node_by_name($node, $table_name);
          $query->condition(data_engine_db_table_to_alias($filter_table) . '.' . $field_name, $values, 'IN');
  
        } // foreach
        
      } // foreach
      
    } // if

    if ($start !== FALSE && $limit !== FALSE) {
      $query->range($start, $limit);
    } // if

    db_set_active('default');

    return data_engine_db_query_to_records($query);

  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [NID: ' . $node->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;

  } // catch

} // data_engine_db_records_from_nodes

/**
 * Returns record count from a dataset.
 */
function data_engine_db_record_count_from_node($node) {

  $records = array();

  $query = data_engine_db_query_from_node($node);

  if ($query) {

    try {
  
      db_set_active('data');
  
      $result = $query->countQuery()->execute()->fetchField();
  
      db_set_active('default');
  
      return $result;
      
    } // try
    catch (Exception $e) {

      db_set_active('default');
      watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
        ' [NID: ' . $node->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
        "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
      return 0;
  
    } // catch

  } // if
  else {

    db_set_active('default');
    return FALSE;

  } // else

} // data_engine_db_record_count_from_node

/**
 * Returns record count from datasets.
 */
function data_engine_db_record_count_from_nodes($node_one, $node_two) {

  $records = array();

  $query = data_engine_db_query_from_nodes($node_one, $node_two);

  if ($query) {

    db_set_active('data');

    $result = $query->countQuery()->execute()->fetchField();

    db_set_active('default');

    return $result;

  } // if
  else {

    db_set_active('default');
    return FALSE;

  } // else

} // data_engine_db_record_count_from_nodes

/**
 * Returns array of field names from given table info.
 */
function data_engine_db_field_names_from_table($table) {

  $fields = array();

  foreach ($table->fields as $field) {
    $fields[] = $field->machine_name;
  } // foreach

  return $fields;

} // data_engine_db_field_names_from_table

function data_engin_db_field_machine_name_to_display_name(&$node, $machine_name) {

  $info = data_engine_db_info_for_node($node);
  
  list($table_name, $field_name) = explode('.', $machine_name);

  foreach ($info->tables as $table) {
    
    if ($table->title == $table_name) {
    
      foreach ($table->fields as $field) {

        if ($field->machine_name == $field_name) {
          return $field->verbose_name;
        } // if       

      } // foreach
    
    } // if
    
  } // foreach
  
  return $field_name;
  
} // data_engin_db_field_machine_name_to_display_name

/**
 * Adds table fields to query.
 */
function data_engine_db_add_table_fields_to_query($table, $query) {
  
  $fields = data_engine_db_field_names_from_table($table);

  foreach ($fields as $field) {
    $query->addField(data_engine_db_table_to_alias($table), $field, data_engine_db_table_to_alias($table) . DATA_ENGINE_DB_PLACEHOLDER . $field);
  } // foreach
  
} // data_engine_db_add_table_fields_to_query

/**
 * Returns field machine and human names for a given dataset.
 */
function data_engine_db_fields_from_dataset($node, $types = FALSE, $info_limit = TRUE) {

  $fields = &drupal_static(__FUNCTION__); 

  if (!isset($fields)) {
    $fields = array();
  } // if
  
  if (!isset($fields[$node->nid])) {

    $wrapper = entity_metadata_wrapper('node', $node);
    $info = json_decode($wrapper->field_query_information->value());

    foreach ($info->tables as $table) {

      foreach ($table->fields as $field) {
  
        if ($types === FALSE || in_array($field->data_type, $types)) {
  
          $table_id_notation = $table->id . '.' . $field->machine_name;
    
          if ($info_limit === FALSE || !isset($info->metadata->fields) || in_array($table_id_notation, $info->metadata->fields)) {
  
            $human_readable_name = ($field->verbose_name) ? $field->verbose_name : $field->field_name;
            $fields[$node->nid][$table->title . '.' . $field->machine_name] = $human_readable_name;

          } // if
  
        } // if
  
      } // foreach
  
    } // foreach

  } // if
  
  return $fields[$node->nid];

} // data_engine_db_fields_from_dataset

/**
 * Returns field machine name of primary key for a given dataset.
 */
function data_engine_db_index_field_from_dataset($node) {

  $wrapper = entity_metadata_wrapper('node', $node);
  $info = json_decode($wrapper->field_query_information->value());

  $first_table = array_shift($info->tables);

  $gkeys = $info->metadata->gkey;

  foreach ($gkeys as $gkey) {

    list($table_id, $index_field) = explode('.', $gkey);

    if ($first_table->id == $table_id) {
      return $first_table->title . '.' . $index_field;
    } // if

  } // foreach

  return FALSE;

} // data_engine_db_index_field_from_dataset

/**
 * Returns geo data from dataset, for mapping.
 */
function data_engine_db_geo_records_from_node($node, $start = FALSE, $limit = FALSE, $centroid = FALSE, $filters = FALSE) {

  try {

    $records = array();

    $info = data_engine_db_info_for_node($node);

    $geo_table = $info->geo_table;

    $query = data_engine_db_geo_query_from_node($node);

    db_set_active('data');

    if ($centroid) {
      $query->addExpression('ST_AsGeoJSON(ST_Centroid(' . data_engine_db_table_to_alias($geo_table) . '.geom))', 'geojson');
    } // if
    else {
      $query->addExpression('ST_AsGeoJSON(' . data_engine_db_table_to_alias($geo_table) . '.geom)', 'geojson');
    } // else

    if ($start !== FALSE && $limit !== FALSE) {
      $query->range($start, $limit);
    } // if

    if (is_array($filters) && count($filters) > 0) {

      foreach ($filters as $filter => $values) {

        list($table_name, $field_name) = explode('.', $filter);
        $filter_table = data_engine_db_table_from_node_by_name($node, $table_name);
        $query->condition(data_engine_db_table_to_alias($filter_table) . '.' . $field_name, $values, 'IN');

      } // foreach

    } // if

    db_set_active('default');

    return data_engine_db_query_to_records($query);

  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [NID: ' . $node->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;

  } // catch

} // data_engine_db_geo_records_from_node

/**
 * Returns geo bounds from dataset, for mapping.
 */
function data_engine_db_geo_bounds_from_node($node) {

  try {

    $records = array();

    $wrapper = entity_metadata_wrapper('node', $node);
    $info = json_decode($wrapper->field_query_information->value());

    $first_table = array_shift($info->tables);
    $geography = data_engine_db_reference_table('ref_geography');
    
    $bounds_table = data_engine_db_geo_table_info($geography[$first_table->tags->geography]->geotable);

    db_set_active('data');

    $query = db_select($bounds_table['title'], $bounds_table['title']);
    $query->addExpression('ST_AsGeoJSON(' . $bounds_table['title'] . '.geom)', 'geojson');

    db_set_active('default');

    $result = data_engine_db_query_to_records($query);

    return $result[0]['geojson'];

  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [NID: ' . $node->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;

  } // catch

} // data_engine_db_geo_bounds_from_node

/**
 * Returns geo bounds from dataset, for mapping.
 */
function data_engine_db_geo_center_from_node($node) {

  try {

    $records = array();

    $wrapper = entity_metadata_wrapper('node', $node);
    $info = json_decode($wrapper->field_query_information->value());

    $geo_table = $info->geo_table;

    $query = data_engine_db_geo_query_from_node($node, TRUE);

    db_set_active('data');

    $query->addExpression('ST_AsGeoJSON(ST_Centroid(ST_Union(' . data_engine_db_table_to_alias($geo_table) . '.geom)))', 'geojson');

    db_set_active('default');

    $result = data_engine_db_query_to_records($query);

    return $result[0]['geojson'];

  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [NID: ' . $node->nid . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;

  } // catch

} // data_engine_db_geo_center_from_node

/**
 * Takes a query, returns records in a standard format.
 */
function data_engine_db_query_to_records($query) {

  // Try cache first.

  $query_text = $query . '';
  $cache_key = 'data_engine_db:' . md5($query_text);
  $cache = cache_get($cache_key);
  
  if ($cache) {
    return $cache->data;
  } // if

  try {

    $records = array();
  
    db_set_active('data');
  
    $result = $query->execute();

    foreach ($result as $record) {
  
      $record_array = (array) $record;
      $altered_array = array();
  
      foreach ($record_array as $key => $value) {
      
        $key_parts = explode(DATA_ENGINE_DB_PLACEHOLDER, $key);
        
        if (count($key_parts) == 1) {
          $altered_array[$key] = $value;
        } // if
        else {
          $altered_array[data_engine_db_alias_to_table_name($key_parts[0]) . '.' . $key_parts[1]] = $value;
        } // else
      
      } // foreach
  
      $records[] = $altered_array;
  
    } // foreach

    db_set_active('default');

    // Cache for 24 hours.

    cache_set($cache_key, $records, 'cache', REQUEST_TIME + 60 * 60 * 48);
  
    return $records;

  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [Query: ' . $query . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return FALSE;

  } // catch

} // data_engine_db_query_to_records

/**
 * Filters records by dataset field metadata.
 */
function data_engine_db_filter_records_by_metadata($records, $node) {

  $filtered = array();
  $info = data_engine_db_info_for_node($node);
  $id_to_name = data_engine_db_table_id_to_name($info);

  if (!isset($info->metadata->fields)) {
    return $records;
  } // if

  $filter = array();

  foreach ($info->metadata->fields as $field) {

    list($table_id, $field_name) = explode('.', $field);
    $filter[] = $id_to_name[$table_id] . '.' . $field_name;

  } // foreach

  foreach ($records as $record) {

    $filtered_record = array();

      foreach ($record as $key => $value) {

        if (in_array($key, $filter)) {
          $filtered_record[$key] = $value;
        } // if

      } // foreach

    $filtered[] = $filtered_record;

  } // foreach

  return $filtered;

} // data_engine_db_filter_records_by_metadata

/**
 * Creates id-to-name array from table metadata.
 */
function data_engine_db_table_id_to_name(&$info) {
  
  $id_to_name = array();
  
  foreach ($info->tables as $table) {
    $id_to_name[$table->id] = $table->title;
  } // foreach

  $id_to_name[$info->geo_table->id] = $info->geo_table->title;

  return $id_to_name;
  
} // data_engine_db_table_id_to_name

/**
 * Returns info for node.
 */
function data_engine_db_info_for_node(&$node) {
  
  $info_sets = &drupal_static(__FUNCTION__); 
  
  if (!isset($info_sets)) {
    $info_sets = array();
  } // if
  
  if (!isset($info_sets[$node->nid])) {
    
    $wrapper = entity_metadata_wrapper('node', $node);
    $info_sets[$node->nid] = json_decode($wrapper->field_query_information->value());

  } // if

  $result = clone $info_sets[$node->nid]; 
  return $result;
  
} // data_engine_db_info_for_node

/**
 * Returns table-name coded pkeys.
 */
function data_engine_db_pkeys_for_node(&$node) {

  $pkeys = &drupal_static(__FUNCTION__); 

  if (!isset($pkeys)) {
    $pkeys = array();
  } // if

  if (!isset($pkeys[$node->nid])) {

    $pkeys[$node->nid] = array();
    $info = data_engine_db_info_for_node($node);
    $gkeys = $info->metadata->gkey;

    foreach ($info->metadata->pkey as $pkey) {
    
      if (in_array($pkey, $gkeys)) {
        $pkey = $info->metadata->display_name;
      } // if

      $pkeys[$node->nid][] = data_engine_db_table_id_to_name_in_field($pkey, $node);

    } // foreach

  } // if
  
  $result = $pkeys[$node->nid];
  return $result;

} // data_engine_db_pkeys_for_node

/**
 * Returns table-name coded gkeys.
 */
function data_engine_db_gkeys_for_node(&$node) {

  $info = data_engine_db_info_for_node($node);
  $gkeys = $info->metadata->gkey;
  
  return data_engine_db_table_id_to_name_in_field($gkeys, $node);

} // data_engine_db_gkeys_for_node

/**
 * Changes field list or single field with table ids to table names.
 */
function data_engine_db_table_id_to_name_in_field($fields, &$node) {

  // If it's an array, pass each item back in and add to new array.

  if (is_array($fields)) {

    $names = array();

    foreach ($fields as $field) {
      $names[] = data_engine_db_table_id_to_name_in_field($field, &$node);
    } // foreach

    return $names;

  } // if

  $info = data_engine_db_info_for_node($node);
  $id_to_name = data_engine_db_table_id_to_name($info);
  
  list($table_id, $field_name) = explode('.', $fields);
  $table_name = $id_to_name[$table_id];
  
  return $table_name . '.' . $field_name;

} // data_engine_db_table_id_to_name_in_field

/**
 * Replaces gkey with display name.
 */
function data_engine_db_set_display_name_attribute($attributes, &$node) {

  $info = data_engine_db_info_for_node($node);
  
  $replaced_attributes = array();
  
  $id_to_name = data_engine_db_table_id_to_name($info);
  list($display_table_id, $display_field) = explode('.', $info->metadata->display_name);
  $display_name = $id_to_name[$display_table_id] . '.' . $display_field;
    
  $gkeys = $info->metadata->gkey;
  $gkey_names = array();
  
  foreach ($gkeys as $gkey) {
    list($gkey_table_id, $gkey_field) = explode('.', $gkey);
    $gkey_names[] = $id_to_name[$gkey_table_id] . '.' . $gkey_field;
  } // foreach
    
  foreach ($attributes as $key => $attribute) {
    
    if (in_array($attribute, $gkey_names)) {
      $replaced_attributes[$display_name] = $display_name;
    } // if
    else {
      $replaced_attributes[$key] = $attribute;
    } // else
    
  } // foreach

  return $replaced_attributes;

} // data_engine_db_set_display_name_attribute

/**
 * Returns a list of NIDs within given bounds.
 */
function data_engine_db_get_datasets_within_bounds($bounds_string) {
  
  // Try cache first.

  $query_text = $query . '';
  $cache_key = 'data_engine_db:datasets_within_bounds:' . md5($bounds_string);
  $cache = cache_get($cache_key);
  
  if ($cache) {
    return $cache->data;
  } // if
  
  $nids = array();
  $nodes = data_engine_db_dataset_nodes();

  foreach ($nodes as $node) {
    
    if (data_engine_db_dataset_count_within_bounds($node, $bounds_string) > 0) {
      $nids[] = $node->nid;
    } // if
    
  } // foreach

  // Cache for 24 hours.

  cache_set($cache_key, $nids, 'cache', REQUEST_TIME + 60 * 60 * 24);
  
  return $nids;
  
} // data_engine_db_get_datasets_within_bounds

/**
 * Determines if given dataset node is within bounds by
 * searching the geo table.
 */
function data_engine_db_dataset_count_within_bounds($node, $bounds_string) {
  
  try {  

    $edges = explode(',', $bounds_string);
    $linestring = 'LINESTRING(' . $edges[0] . ' ' . $edges[1] . ',' . $edges[2] . ' ' . $edges[3] . ')';
    
    $wrapper = entity_metadata_wrapper('node', $node);
    $info = json_decode($wrapper->field_query_information->value());
    
    $geo_table = $info->geo_table;
  
    $query = data_engine_db_geo_query_from_node($node, TRUE);
  
    db_set_active('data');
  
    $query->addField(data_engine_db_table_to_alias($geo_table), 'geom', 'geom');
    $query->where("ST_Intersects(
      ST_GeomFromText(
        ST_AsText(
          ST_Envelope('" . $linestring . "'::geometry)
        ), 4269
      ), ST_Transform(" . data_engine_db_table_to_alias($geo_table) . ".geom, 4269)
    )");
    
    $count = $query->countQuery()->execute()->fetchField();
  
    db_set_active('default');
  
    return $count;
    
  } // try
  catch (Exception $e) {

    db_set_active('default');
    watchdog('data_engine_db', 'DB Error: ' . $e->getMessage() .
      ' [Query: ' . $query . '; Line: ' . $e->getLine() . '; File: ' . $e->getFile() . ']' .
      "\n" . $e->getTraceAsString(), array(), WATCHDOG_ERROR);
    return 0;

  } // catch
    
} // data_engine_db_dataset_count_within_bounds
